language: node_js
node_js:
  - 10

os: linux

env:
  - global:
    - JWT_SECRET=notVerySecret
    - DB_NAME=couplesdiarytest

cache:
  directories:
    - node_modules

before_script:
  npx lerna bootstrap

script:
  ./scripts/test.sh
